### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by nishantc7** [nishantc7/crwn-clothing#3]

**Comment by Lovegupta112** [comment]
Ok ai can , you mean to say that there is button on which if someone click then the dark mode should be enabled. Am I ryt ?? 
If I am right , so plz assign me this issue

**Comment by nishantc7** [comment]
Yes, sure, but where do you plan to place the button?

**Comment by Lovegupta112** [comment]
Would it be ok , if I add this right top corner

**Comment by nishantc7** [comment]
> Would it be ok , if I add this right top corner

Yeah go ahead 👍
